# Imports

In [1]:
import pandas as pd
import networkx as nx
import re

# Load data

In [2]:
DATA_PATH = '../Data/test_KTH_only.json'
SAVE_GRAPH_PATH = 'graph/'

In [3]:
df = pd.read_json(DATA_PATH)
df.head()

,PID,Title,Keywords,Content,Authors
0,680998,2D Mapping Solutionsfor Low Cost Mobile Robot,[],"\nMapping, localization, and path-planning are...","[WANG, XUAN]"
1,1903661,3D Scene Reconstruction using Diffusion Models...,"[Computer Vision, 3D Reconstruction, Text-to-3...",\nState of the art text-to-image diffusion mod...,"[Persson, Carl]"
2,1229779,3D Shape Detection for Augmented Reality (3D f...,"[3D Machine Learning, object detection, comput...","\nIn previous work, 2D object recognition has ...","[Anadon Leon, Hector]"
3,1888229,3D Shape Retrieval Meets Machine Learning : Im...,"[3D shape retrieval, pattern recognition, mach...",\nIn the rapidly evolving realm of CAD model r...,"[Hazara, Omid]"
4,1245296,3D YOLO: End-to-End 3D Object Detection Using ...,"[Computer vision, Machine Learning, Autonomous...","\nFor safe and reliable driving, it is essenti...","[Al Hakim, Ezeddin]"

# Build graph

In [4]:
ignore = set([
    "DEPARTMENT OF ZOOLOGY, STOCKHOLM UNIVERSITY, STOCKHOLM, SWEDEN.)",
    "JHERONIMUS ACAD DATA SCI, NL-5211 DA SHERTOGENBOSCH, NETHERLANDS.)",
    "DEPARTMENT OF ZOOLOGY, STOCKHOLM UNIVERSITY, STOCKHOLM, SWEDEN)",
    "ENJOYOR CO., LTD, HANGZHOU 310030, CHINA.)",
    "DIGITAL FUTURES, KTH, STOCKHOLM)",
    "MOHAMED BIN ZAYED UNIVERSITY OF ARTIFICIAL INTELLIGENCE)",  
])

In [5]:
def extract_author_names(authors):
    names = []
    for author in authors.split(';'):
        match = re.match(r'^([^\[\(\]]+)', author)
        if match:
            names.append(match.group(1).strip().upper())
    return names

In [6]:
g = nx.Graph()

for _, row in df.iterrows():
    author_names = [name.upper() for name in row.Authors]
    for i in range(0, len(author_names)):
        if author_names[i] in ignore:
            continue
        for j in range(i+1, len(author_names)):
            if author_names[j] in ignore:
                continue
            g.add_edge(author_names[i], author_names[j])

# Authors to author ids

In [8]:
author_ids = {name: i for i, name in enumerate(g.nodes())}
author_ids

{'STRÖMBERG, PHILIP': 0,
 'BLOMKVIST KARLSSON, VERA': 1,
 'RENMAN, CASPER': 2,
 'FRISTEDT, HAMPUS': 3,
 'ISHII, SHOTARO': 4,
 'LJUNGGREN, DAVID': 5,
 'BAJALLAN, REBWAR': 6,
 'HASHI, BURHAN': 7,
 'FREDRIKSON, RASMUS': 8,
 'DAHL, JONAS': 9,
 'TASKIN, KASIM': 10,
 'DINLER, MUSTAFA': 11,
 'SALMAN, ALZAHRAA': 12,
 'HANNA, ROUWAYD': 13,
 'ANDERSSON, PETTER': 14,
 'WÖRLUND, ROBERT': 15,
 'HAGLUND, ISAC': 16,
 'JOHANSSON, LISA': 17,
 'ALAM, JOY': 18,
 'LJUNGEHED, JESPER': 19,
 'BESSELING, JOHAN': 20,
 'RENSTRÖM, ANDERS': 21,
 'FORSBERG, TOM-HENRIK': 22,
 'SUNDSTRÖM, JOHAN': 23,
 'LARSSON, MATTIAS': 24,
 'KIRICHENKO, DAN': 25,
 'RANDLEFF, VERONICA': 26,
 'SCHWERMER, PATRIK': 27,
 'STREIJFFERT, NILS': 28,
 'TEGELMARK, FRANS': 29,
 'SUNDLÖF, CLAUDIUS': 30,
 'KRANTZ, GUSTAV': 31,
 'SVEBRANT, HENRIK': 32,
 'SVANBERG, JOHN': 33,
 'GUNÉR, GUSTAF': 34,
 'HAIDER, ADIBBIN': 35,
 'VARATHARAJAH, THUJEEPAN': 36,
 'VICTOR, ERIKSSON': 37,
 'WEDIN, MATTIAS': 38,
 'BENGTSSON, ISAK': 39,
 'RAKSANYI, EMIL': 40,
 'DACKANDER, ERIK': 41,
 'NOLANDER, CHRISTOFER': 42,
 'STRÖMDAHL, AMANDA': 43,
 'MARRIKIE, RAMI': 44,
 'RACHED, WALED': 45,
 'LARSSON, THIMMY': 46,
 'WEDIN, JONAS': 47,
 'BURVALL, BENJAMIN': 48,
 'OLEGÅRD, JOHANNES': 49,
 'BJÖRCK, ERIK': 50,
 'OMSTEDT, FREDRIK': 51,
 'ALVAEUS, EDVIN': 52,
 'LINDÉN, LUDVIG': 53,
 'KJELLBERG, GUSTAV': 54,
 'KÄLVEGREN, HENRIK': 55,
 'KLAESSON, ERIC': 56,
 'DAHLIN, VICTOR': 57,
 'LUNDHOLM, JESPER': 58,
 'LEDÉUS, JOHAN': 59,
 'ACHARYA, JALDEEP': 60,
 'FRÖBERG, LUDVIG': 61,
 'ÖSTLING, MARCUS': 62,
 'LILJA, JOAKIM': 63,
 'JAFARI, MIKAEL': 64,
 'OLBE, JOEL': 65,
 'TABARI, MICHEL': 66,
 'SULTANI, RAWAND': 67,
 'ANDERSSON, OSKAR': 68,
 'REYNA MARQUEZ, STEFFANY': 69,
 'LUNDQVIST, MELVIN': 70,
 'FORSBERG, AGNES': 71,
 'SÖRME, JACOB': 72,
 'EDWARDS, TOBIAS': 73,
 'HEYMAN, HUGO': 74,
 'BRANDEFELT, LOVE': 75,
 'SCHWALBE LEHTIHET, OLIVER': 76,
 'ÅRYD, VIKTOR': 77,
 'BORG, CAROLINE W.': 78,
 'DACKEBRO, ERIK': 79,
 'JAGELID, MICHELLE': 80,
 'MOVIN, MARIA': 81,
 'GRANSKOG, TIM': 82,
 'STRIGÉR, AMANDA': 83,
 'PODOBAS, ARTUR': 84,
 'BRORSSON, MATS': 85,
 'ENGELHARDT, SARA': 86,
 'HANSSON, EMMELI': 87,
 'EFFATI, SHAYAN': 88,
 'ALIPOOR, DONIA': 89,
 'AVELLAN-HULTMAN, DAVID': 90,
 'GUNNBERG QUERAT, EMIL': 91,
 'ANDERSSON, VILHELMINA': 92,
 'SELLER FREDLUND, JOHAN': 93,
 'ADAMSSON, MARCUS': 94,
 'VORKAPIC, ALEKSANDAR': 95,
 'BHAT, SRIHARSHA': 96,
 'TORROBA, IGNACIO': 97,
 'ÖZKAHRAMAN, ÖZER': 98,
 'BORE, NILS': 99,
 'SPRAGUE, CHRISTOPHER': 100,
 'XIE, YIPING': 101,
 'STENIUS, IVAN': 102,
 'SEVERHOLT, JOSEFINE': 103,
 'LJUNG, CARL': 104,
 'FOLKESSON, JOHN': 105,
 'ÖGREN, PETTER': 106,
 'BLOMQVIST, NIKLAS': 107,
 'HYGERTH, HENRIK': 108,
 'ZAMANISIBONI, AMIRREZA': 109,
 'OECHTERING, TOBIAS J.': 110,
 'SKOGLUND, MIKAEL': 111,
 'LAPTEV, IVAN': 112,
 'LINDEBERG, TONY': 113,
 'MO, FAN': 114,
 'CHAPLIN, JACK C.': 115,
 'SANDERSON, DAVID': 116,
 'REHMAN, HAMOOD UR': 117,
 'MONETTI, FABIO MARCO': 118,
 'MAFFEI, ANTONIO': 119,
 'RATCHEV, SVETAN': 120,
 'BERGLUND, ERIK': 121,
 'SCHYFFERT, JANNE': 122,
 'JIN, JUNCHEN': 123,
 'MA, XIAOLIANG': 124,
 'BAUMANN, CHRISTOPH': 125,
 'NÄSLUND, MATS': 126,
 'GEHRMANN, CHRISTIAN': 127,
 'SCHWARZ, OLIVER': 128,
 'THORSEN, HANS': 129,
 'BARBETTE, TOM': 130,
 'TANG, CHEN': 131,
 'YAO, HAORAN': 132,
 'KOSTIC, DEJAN': 133,
 'MAGUIRE JR., GERALD Q.': 134,
 'PAPADIMITRATOS, PANAGIOTIS': 135,
 'CHIESA, MARCO': 136,
 'SANDSTRÖM, JESPER': 137,
 'OHLSSON, JONATHAN': 138,
 'BROMMUND, ANDREAS': 139,
 'SKEPPSTEDT, DAVID': 140,
 'JANSSON, NICLAS': 141,
 'HOFFMAN, JOHAN': 142,
 'MEINKE, KARL': 143,
 'NIU, FEI': 144,
 'OLOFSSON, NINA': 145,
 'FAKIH, NIVIN': 146,
 'BASKIN, FEDOR': 147,
 'SCOTT-ROBBERT, EMIL': 148,
 'GREN, OLAF': 149,
 'MAGNUSSON, DENNIS': 150,
 'HALLSTRÖM, ERIC': 151,
 'HELLSTENIUS, SASHA': 152,
 'SVANTESSON, DAVID': 153,
 'EKLUND, MARTIN': 154,
 'IAKYMCHUK, ROMAN': 155,
 'JORDAN, HERBERT': 156,
 'PENG, IVY BO': 157,
 'MARKIDIS, STEFANO': 158,
 'LAURE, ERWIN': 159,
 'HYYRYNEN, FREDRIK': 160,
 'LIGNERCRONA, MARCUS': 161,
 'KIM, HOKEUN': 162,
 'BROMAN, DAVID': 163,
 'LEE, EDWARD A': 164,
 'ZIMMER, MICHAEL': 165,
 'SHRIVASTAVA, AVIRAL': 166,
 'OH, JUNKWANG': 167,
 'FISCHER HORN AF RANTZIEN, DOUGLAS': 168,
 'WEIGELT, CHRISTIAN': 169,
 'LARSEN, CAROLINE': 170,
 'RYMAN, ELIN': 171,
 'STENSÖ, ISAK': 172,
 'ROSENBACK, ANDREAS': 173,
 'GRIGGIO, CARLA': 174,
 'ROMERO, MARIO': 175,
 'GRADOS, FIORELLA': 176,
 'MOHAMMADI, AREF': 177,
 'JOHANSSON, JONAS': 178,
 'RUNNMAN, KENNETH': 179,
 'BLOM, ALEXANDER': 180,
 'THORSEN, SOFIE': 181,
 'SCHWIELER, MATHILDA': 182,
 'FREDIN HASLUM, ERIC': 183,
 'OLBY, LINNEA': 184,
 'THOMANDER, ISABEL': 185,
 'KOSONEN, IISAKKI': 186,
 'WONG, BONNY': 187,
 'BOLDT-CHRISTMAS, AXEL': 188,
 'RIESCHEL, EMILIA': 189,
 'NILSSON, EMM': 190,
 'ALNESS BORG, AXEL': 191,
 'ENSTRÖM, MARCUS': 192,
 'KANG, EUNSUK': 193,
 'EDWARD, LEE': 194,
 'MAKENZIUS, MICAEL': 195,
 'BYLERIUS, JONAS': 196,
 'CAKICI, BAKI': 197,
 'BOMAN, MAGNUS': 198,
 'CARLSSON, TOBIAS': 199,
 'STRÖMBERG, OSKAR': 200,
 'L I N D B L O M, M A T H I A S': 201,
 'W I E N E R, L U C A S': 202,
 'QUEZADA CRUZ, PATRICIO IGNACIO': 203,
 'FALK, PONTUS': 204,
 'QUEZADA, IGNACIO': 205,
 'BJÖRKMAN, MÅRTEN': 206,
 'KRAGIC, DANICA': 207,
 'BRUNNSTRÖM, KJELL': 208,
 'EKLUNDH, JAN-OLOF': 209,
 'KRAVCHENKO, ALEXANDER': 210,
 'MARCHETTI, GIOVANNI LUCA': 211,
 'POLIANSKII, VLADISLAV': 212,
 'VARAVA, ANASTASIIA': 213,
 'POKORNY, FLORIAN T.': 214,
 'GÓMEZ, PAULA': 215,
 'DO, ELLEN YI-LUEN': 216,
 'KAZZI, DANIEL ALEXANDER': 217,
 'WINBERG, VINCENT': 218,
 'FRÖBERG, TOBIAS': 219,
 'NORDSTRÖM, LUDWIG': 220,
 'PIERROU, CAJSA': 221,
 'MALMSTRÖM, OSKAR': 222,
 'TRUEDSSON, MAX': 223,
 'WESTERGREN, ERIK': 224,
 'RINGSTRÖM1, VINCENT': 225,
 'ALVAREZ FUNCKE, ILEY': 226,
 'AFROZE, TONIMA': 227,
 'ROSÉN GARDELL, MOA': 228,
 'BROKKING, ALEXANDER': 229,
 'WINK, MICHAEL': 230,
 'SOLEIMANIFARD, SIAVASH': 231,
 'GUROV, DILIAN': 232,
 'GROZMAN, VLADIMIR': 233,
 'NORMAN, CHRISTOPHER': 234,
 'SÖDERBERG, ERIC': 235,
 'RÅHLÉN, JAKOB': 236,
 'KIDANE, PAULOS': 237,
 'BONDS, AUGUST': 238,
 'WASS, MARTIN': 239,
 'WANG, THOMAS': 240,
 'DESPINOY, EVA': 241,
 'NARROWE DANIELSSON, SARAH': 242,
 'TELL, NOAH': 243,
 'THUN, ANTON': 244,
 'KAMRAS, LUDWIG': 245,
 'MATSLOVA, WILLIAM': 246,
 'HASSAN, ABDALLAH': 247,
 'SYED, ARSALAN': 248,
 'WILTSCHI, K.': 249,
 'PINZ, A.': 250,
 'DANELL HÅKANSSON, AUGUST': 251,
 'JOHNSSON, MIRJA': 252,
 'WESTLIN, CAROLINA': 253,
 'MÅRTENSSON, ANDREAS': 254,
 'NILSSON, WILLIAM': 255,
 'ARVIDSSON, JAKOB': 256,
 'ALINDER, HELENA': 257,
 'NILSSON, JOSEFIN': 258,
 'CHIEN, STEVEN WEI DER': 259,
 'SISHTLA, CHAITANYA PRASAD': 260,
 'JUN, ZHANG': 261,
 'BELLEM WESTIN, HUGO': 262,
 'SHI, KAROLINA': 263,
 'MILD, MARKUS': 264,
 'MÄÄTTÄ  VINKLER, ALEXIS': 265,
 'BRYNIELSSON, JOEL': 266,
 'ARNBORG, STEFAN': 267,
 'WIPPICH, MAX': 268,
 'MICKOLS, KRISTIN': 269,
 'VUONG, HARRY': 270,
 'LILJEGREN, SYLWESTER': 271,
 'ELIN, KARAGÖZ': 272,
 'ALICE, HEAVEY': 273,
 'HEISKANEN, ANDREAS': 274,
 'JOHANSSON, ERIK': 275,
 'MATTILA, MAX': 276,
 'SALMAN, HASSAN': 277,
 'EKNE, SAMUEL': 278,
 'GYLLEUS, KARL': 279,
 'LIDBERG, PÄR': 280,
 'ROLAND, PER': 281,
 'LIDBERG, PER': 282,
 'LUTTU, JOHAN': 283,
 'ROSQUIST, OSCAR': 284,
 'KOSKI, ALEXANDER': 285,
 'PERSSON, JENNIFER': 286,
 'WESTER, PHILIP': 287,
 'HEIDING, FREDRIK': 288,
 'LAGERSTRÖM, ROBERT': 289,
 'PETTERSSON, LARS': 290,
 'LUNDELL JOHANSSON, CHRISTOFFER': 291,
 'KOLLIN, FELIX': 292,
 'BAVEY, ADEL': 293,
 'MUIR, MACAULLY': 294,
 'WIKSTRÖM, JOHAN': 295,
 'NILSSON, OSCAR': 296,
 'YNGWE, NOEL': 297,
 'OLDENSAND, VICTOR': 298,
 'HAGLUND, SIMON': 299,
 'FRIDSTRÖM, HENRIK': 300,
 'SJÖBERG, LINUS': 301,
 'BERGMAN, AUGUST': 302,
 'ERICSSON, SONJA': 303,
 'MEJDI, SAMI': 304,
 'DJOWEINI, CAMJAR': 305,
 'GARTZ, MADELEINE': 306,
 'LINDERBRANDT, IDA': 307,
 'LINDHOLM, TIMMY': 308,
 'JONNERBY, OLOF': 309,
 'BLOMQVIST, FREDRIK': 310,
 'HULTCRANTZ, EMIL': 311,
 'ANDERSON, THOMAS': 312,
 'CANINI, MARCO': 313,
 'KIM, JONGYUL': 314,
 'KWON, YOUNGJIN': 315,
 'PETER, SIMON': 316,
 'REDA, WALEED': 317,
 'SCHUH, HENRY': 318,
 'WITCHEL, EMMETT': 319,
 'YADAV, RITU': 320,
 'NASCETTI, ANDREA': 321,
 'BAN, YIFANG': 322,
 'DEL TEJO CATALÁ, OMAR': 323,
 'MASIÁ FUSTER, LUIS': 324,
 'PAN, TIANYANG': 325,
 'VERGINIS, CHRISTOS': 326,
 'WELLS, ANDREW': 327,
 'KAVRAKI, LYDIA': 328,
 'DIMAROGONAS, DIMOS V.': 329,
 'ANSIN, RASMUS': 330,
 'LUNDBERG, DIDRIK': 331,
 'SJÖBERG, JONAS': 332,
 'NISSAR, HUGO': 333,
 'LUNDÉN, DANIEL': 334,
 'ÇAYLAK, GIZEM': 335,
 'RONQUIST, FREDRIK': 336,
 'DAM, MADS': 337,
 'MAYER, H.': 338,
 'ECKSTEIN, W.': 339,
 'STEGER, C.': 340,
 'BAUMGARTNER, A.': 341,
 'LI, MENG-XIANG': 342,
 'JONSSON, LEIF': 343,
 'MAGNUSSON, MÅNS': 344,
 'SANDAHL, KRISTIAN': 345,
 'VILLANI, MATTIAS': 346,
 'ELDH, SIGRID': 347,
 'LISON, P.': 348,
 'MEENA, RAVEESH': 349,
 'GUNNING, CHRISTOFFER': 350,
 'FORSLUND, DANIEL': 351,
 'HENDERED, VICTORIA': 352,
 'JÖNSSON, AUGUST': 353,
 'VÄLJA, MARGUS': 354,
 'FRANKE, ULRIK': 355,
 'WELANDER, SONJA': 356,
 'FISCHER, EVELINA': 357,
 'TARELIUS, THERESE': 358,
 'KOTZEV, LUBOMIR': 359,
 'ROLLEBERG, NIKLAS': 360,
 'EVILEVITCH, ANTON': 361,
 'INGRAM, ROBERT': 362,
 'REICHLIN, ALFREDO': 363,
 'YIN, HANG': 364,
 'GHADIRZADEH, ALI': 365,
 'HELDNER, MATTIAS': 366,
 'HJALMARSSON, ANNA': 367,
 'EDLUND, JENS': 368,
 'NILSSON, ELLIOT': 369,
 'WENSINK, LIZA': 370,
 'YIN, EMMY': 371,
 'WIJK, KLAS': 372,
 'SVEDIN, MARTIN': 373,
 'GEUNA, TROLLE': 374,
 'NILSSON, ANDREAS': 375,
 'SPÅNG, ANTON': 376,
 'BROLIN ECHEVERRIA, PAOLO': 377,
 'WESTERMARK, JOAKIM': 378,
 'GEDIN, SEBASTIAN': 379,
 'HOLM, JAKOB': 380,
 'BERG, JOHAN': 381,
 'MEBRAHTU REDI, DANIEL': 382,
 'WANG, PO-AN': 383,
 'TZENG, RUO-CHUN': 384,
 'PROUTIERE, ALEXANDRE': 385,
 'ERGENEKON, EMRE BERGE': 386,
 'ERIKSSON, PETTER': 387,
 'LÖVMAR, ANTON': 388,
 'CLASSON, PER': 389,
 'MELANDER, ANTON': 390,
 'HALVORD, ERIK': 391,
 'JOHANSSON, TOM': 392,
 'CHARPENTIER, VIKTOR': 393,
 'HUANG, SHUN': 394,
 'CARLSSON, JACOB': 395,
 'KULTALA, HENRIK': 396,
 'PERSSON, SIMON': 397,
 'KARLSSON, RAGNHILD': 398,
 'ERIKSSON, MIKAEL': 399,
 'VAN HOOVELS, KEVIN': 400,
 'XUAN, XING': 401,
 'CUARTERO, MARIA': 402,
 'GIJSSEL, MAARTEN': 403,
 'SWAREN, MIKAEL': 404,
 'CRESPO, GASTON A.': 405,
 'OSNES, SIMON': 406,
 'BERG, AMANDA': 407,
 'NEPPARE, CHRISTOFFER': 408,
 'BLOMBERG, PONTUS': 409,
 'MANN, ANNA': 410,
 'HÖFT, OLIVIA': 411,
 'PETTERSSON, CHRISTOFFER': 412,
 'SCHMIDT, ERIC': 413,
 'VIKLUND, ALEXANDER': 414,
 'NIMSTAD, EMMA': 415,
 'KOTTORP, MAX': 416,
 'JÄDERBERG, FILIP': 417,
 'VALLERYD, MATILDA': 418,
 'ASKLING, THERESE': 419,
 'MALMGREN, MAX': 420,
 'ÅHAMMAR, ULF': 421,
 'WILTSCHI, KLAUS': 422,
 'PINZ, AXEL': 423,
 'NORDSTRÖM, RICHARD': 424,
 'TÄNGMARK, ANNIKA': 425,
 'JAVANMARDI, RAMTIN': 426,
 'REHMAN, DAWOOD': 427,
 'TUMWA, PHILIP': 428,
 'MÖTTUS, SANDRA': 429,
 'ROY, DEBADITYA': 430,
 'KOMINI, VANGJUSH': 431,
 'GIRDZIJAUSKAS, SARUNAS': 432,
 'SEGERSVÄRD, OSKAR': 433,
 'SÅNGBERG, DENNIS': 434,
 'PERS, AXEL': 435,
 'ORRE, ADAM': 436,
 'LU, CHI JEN': 437,
 'LINDGREN, LEONARD': 438,
 'KVASOV, MAXIM': 439,
 'SHARIF RAZAVIAN, ALI': 440,
 'AZIZPOUR, HOSSEIN': 441,
 'SULLIVAN, JOSEPHINE': 442,
 'CARLSSON, STEFAN': 443,
 'TYSELL SUNDKVIST, LEIF': 444,
 'PERSSON, EMIL': 445,
 'LORENTZ, ROBERT': 446,
 'EK, OSKAR': 447,
 'SVÄRD, MIKAEL': 448,
 'RUMMAN, PHILIP': 449,
 'SOMMAR, FREDRIK': 450,
 'WIELONDEK, MILOSZ': 451,
 'LÖWBEER, RIKARD': 452,
 'GÖRANSSON, EMIL': 453,
 'UGGELBERG, RICHARD': 454,
 'LUNDBLOM, ANDREAS': 455,
 'LILLTHORS, CHRISTOPHER': 456,
 'PHILIPSON, SAMUEL': 457,
 'ROOS, QUINTUS': 458,
 'LILLIESKÖLD, WILLIAM': 459,
 'LUNDIN, LARS': 460,
 'DATH, CARL': 461,
 'PERSSON, MAX': 462,
 'DABIRI, ARASH': 463,
 'BROBERG, FELIX': 464,
 'ERIKSSON, EMELIE': 465,
 'ERIKSSON, OLIVER': 466,
 'LINDBLOM, WILLIAM': 467,
 'ODELIUS, NORA': 468,
 'REINHOLDSSON, ISAK': 469,
 'LE, TONY': 470,
 'KARLBERG, PONTUS': 471,
 'HOCKER, SIMON': 472,
 'HAMMARSTRAND, ANDREAS': 473,
 'ALEKSEENKO, ANDREY': 474,
 'PALL, SZILARD': 475,
 'DE BLASIO, SIMONE': 476,
 'EKSTEDT KARPERS, FREDRIK': 477,
 'GYLLENRAM, JONATHAN': 478,
 'GISSLÉM, FREDRIK': 479,
 'SANNEMO, JOHAN': 480,
 'LINDHOLM, SIMON': 481,
 'JONSSON SJÖDIN, ADRIAN': 482,
 'LUNDQVIST, ALEXANDER': 483,
 'HANEKLINT, CARL': 484,
 'JOO, YO HAN': 485,
 'WÅREUS, LINUS': 486,
 'WÄLLSTEDT, MAX': 487,
 'HANSJONS VEGEBORN, VICTOR': 488,
 'RAHMANI, HAKIM': 489,
 'ANDERSSON, RASMUS': 490,
 'TJERNELL, ERICA': 491,
 'SANDELIUS, HUGO': 492,
 'FORSELL, SIMON': 493,
 'WICKMAN, TOMAS': 494,
 'ÖHMAN, EMIL': 495,
 'LINDBERG, ADAM': 496,
 'GERHOLM, GUSTAV': 497,
 'DUBERG, DANIEL': 498,
 'TIDESTRÖM, JAKOB': 499,
 'KRATZ, JAKOB': 500,
 'LUTHMAN, VIKTOR': 501,
 'KARLSSON, HERMAN': 502,
 'WILLIAMS, SEBASTIAN': 503,
 'ADZEMOVIC, HARIS': 504,
 'SANDOR, ALEXANDER': 505,
 'BOSTRÖM, PETER': 506,
 'FILIPSSON, MELKER': 507,
 'JANSE, AUGUST': 508,
 'REDGERT, REBECCA': 509,
 'ROMULD, DANIEL': 510,
 'RUHMÉN, MARKUS': 511,
 'ÖHMAN, JOEY': 512,
 'KUDLICKA, JAN': 513,
 'SENDEROV, VIKTOR': 514,
 'LINDE, OSKAR': 515,
 'SCHAEFER, INA': 516,
 'BERGDORF, JOHAN': 517,
 'NORMAN, JESPER': 518,
 'ÅSLUND, JACOB': 519,
 'DAHLIN, ANTON': 520,
 'SAMUELSSON, AXEL': 521,
 'HELLGREN, ROBIN': 522,
 'SOCOLOVSCHI, SERGHEI': 523,
 'BWOGI, ANDREW': 524,
 'DAGDELEN, TUNCAY': 525,
 'KAMELABAD, ALIREZA M.': 526,
 'ENGWALL, OLOV': 527,
 'SKANTZE, GABRIEL': 528,
 'ZHAO, XIN': 529,
 'HALLER, PHILIPP': 530,
 'INGEMARSSON, GABRIEL': 531,
 'KODET, RICKARD': 532,
 'SETTERQUIST, DAN': 533,
 'SKEPPSTEDT, PETER': 534,
 'EDLUND, JOAKIM': 535,
 'BERNTSSON, FREDRIK': 536,
 'FOKIN, DENNIS': 537,
 'HAGROT, JOEL': 538,
 'LINDSTEDT, GUSTAF': 539,
 'RUNELÖV, MARTIN': 540,
 'ERICSSON, ANDREAS': 541,
 'DÖRINGER KANA, FILIP': 542,
 'NIKOU, ALEXANDROS': 543,
 'TUMOVA, JANA': 544,
 'BHATNAGAR, KUNAL': 545,
 'EKNER, GUSTAV': 546,
 'BORGSTRÖM, JOHANNES': 547,
 'ISACSON, JONAS': 548,
 'LINDBLOM, EMIL': 549,
 'LUNDSTRÖM, ANDERS': 550,
 'FERNAEUS, YLVA': 551,
 'WINDLIN, CHARLES': 552,
 'BOGDAN, CRISTI': 553,
 'EKLUND, ANNA': 554,
 'JACOBSSON, SOFIA': 555,
 'BOUVIN, DANIEL': 556,
 'HAMBERG, ERIK': 557,
 'ÖSTLUND, FREDRIK': 558,
 'FAHLMAN, ERIK': 559,
 'CORCORAN, DIARMUID': 560,
 'ANDIMEH, LOGMAN': 561,
 'ERMEDAHL, ANDREAS': 562,
 'KREUGER, PER': 563,
 'SCHULTE, CHRISTIAN': 564,
 'GÜRDÜR, DIDEM': 565,
 'RAIZER, KLAUS': 566,
 'EL-KHOURY, JAD': 567,
 'BONINO QUINTANA, JOAQUIN': 568,
 'FAGERLIND, SEBASTIAN': 569,
 'BOSKOS, DMITRIS': 570,
 'JOSILO, SLADANA': 571,
 'DAN, GYÖRGY': 572,
 'ALKATHIRI, ABDUL AZIZ': 573,
 'GIARETTA, LODOVICO': 574,
 'SAHLGREN, MAGNUS': 575,
 'GAMBA, MATTEO': 576,
 'ENGLESSON, ERIK': 577,
 'KARLBRG, TOBIAS': 578,
 'MALMGREN, JENNIFER': 579,
 'CUMBANE, SILVINO PEDRO': 580,
 'GIDOFALVI, GYÖZÖ': 581,
 'FINNMAN, PETER': 582,
 'WINBERG, MAX': 583,
 'BABIKER, AYAH': 584,
 'BASTA, TINA': 585,
 'HELLSTRÖM, PER': 586,
 'JACCOPUCCI, VICTOR': 587,
 'ALENSKOG BERG, CHRISTOFFER': 588,
 'TOMSIC, NIKLAS': 589,
 'LIND, EMMA': 590,
 'STAHRE, MATTIAS': 591,
 'POKLUKAR, PETRA': 592,
 'MURRAY, LAWRENCE': 593,
 'SCHÖN, THOMAS': 594,
 'JÄGBERG, ISAK': 595,
 'STICHEL, MATS': 596,
 'JANSSON, LUDVIG': 597,
 'ENGSTRÖM, ROBIN': 598,
 'ANDRÉE, JONAS': 599,
 'PETERS, CHRISTOPHER': 600,
 'THURESSON, BJÖRN': 601,
 'KÄRRBY, ANDREAS': 602,
 'TENNANDER, MAJA': 603,
 'JAMIL AHSAN, ADNAN': 604,
 'LANDBERG, DANIEL': 605,
 'STIGEBORN, OLIVIA': 606,
 'WALLBERG, FRIDA': 607,
 'GRIPPE, EDWARD': 608,
 'LÖNNERBERG, MATTIAS': 609,
 'SAHINDAL, BORAN': 610,
 'HAMRA, SAM': 611,
 'BÄCKSTRÖM, SANDRA': 612,
 'FREDIN HASLUM, JOHAN': 613,
 'BROLIN, MORGAN': 614,
 'LEDIN, ERIK': 615,
 'WENNLÖF, HÅKAN': 616,
 'KARIPIDOU, KELLY': 617,
 'BRODIN, RASMUSS': 618,
 'LINDEMALM, KLARA': 619,
 'DAHL, JOHAN': 620,
 'CERDA, BENJAMIN': 621,
 'MOGADDAM, ANTON': 622,
 'MUHAMMAD, KHAN': 623,
 'AMGREN, PONTUS': 624,
 'OLAUSSON, EMIL': 625,
 'IBRAHIM, AHMEDHADI BASHIR': 626,
 'ALSHIKHA, BESHER': 627,
 'BADAR, MIAN': 628,
 'THAKRAR, NIKHIL': 629,
 'HORNDAHL, ANDREAS': 630,
 'KAATI, LISA': 631,
 'MÅRTENSON, CHRISTIAN': 632,
 'SVENSON, PONTUS': 633,
 'HEIMISDÓTTIR, HRAFNDÍS BRÁ': 634,
 'SKÄRBY, JILL': 635,
 'ANDREASSON, ALBIN': 636,
 'MELLBERG, ROBERT': 637,
 'GÅRDING, JONAS': 638,
 'BERGHOLM, MARCUS': 639,
 'KRONVALL, VIKTOR': 640,
 'ORDOZGOITI, BRUNO': 641,
 'GIONIS, ARISTIDES': 642,
 'CHOI, EUN-HYE': 643,
 'ARTHO, CYRILLE': 644,
 'KITAMURA, TAKASHI': 645,
 'MIZUNO, OSAMU': 646,
 'YAMADA, AKIHISA': 647,
 'KLAUCK, HARTMUT': 648,
 'NA NONGKAI, DANUPON': 649,
 'PANDURANGAN, GOPAL': 650,
 'ROBINSON, PETER': 651,
 'ABDLWAFA, ALAN': 652,
 'EDMAN, HENRIK': 653,
 'FRIBERG, OSCAR': 654,
 'ENGLESSON, BJÖRN': 655,
 'SAQIB, EHSAN': 656,
 'HÖSTKLINT, NIKLAS': 657,
 'LARSSON, JESPER': 658,
 'OLSSON, ANNA': 659,
 'NORDLÖF, DENISE': 660,
 'BAKHSHIYEVA, AFRUZ': 661,
 'BEREFELT, GABRIEL': 662,
 'WEST, BALTHAZAR': 663,
 'WENGELIN, MARCUS': 664,
 'LI, LISA': 665,
 'VYTH, JAKOB': 666,
 'KNOWLES, OSCAR': 667,
 'PETERSON, CARL': 668,
 'LINDBERG, JOAKIM': 669,
 'STEIER, MARTIN': 670,
 'LINDQUIST, SINNA': 671,
 'LUOTSINEN, LINUS': 672,
 'FALL, JAKOB': 673,
 'KLINC, REBECCA': 674,
 'ELIASSON, PHILIP': 675,
 'ROSÉN, NIKLAS': 676,
 'AXELSSON, JOHANNA': 677,
 'BERNELIND, SARAH': 678,
 'CEDER, FREDERICK': 679,
 'NORDIN, ALEXANDRA': 680,
 'JANSSON, ANTON': 681,
 'UGGLA LINGVALL, KRISTOFFER': 682,
 'BLADES, CHRISTOFFER': 683,
 'BOYRAZ, FILIZ': 684,
 'SJÖHOLM, THOMAS': 685,
 'KARLBOM, DAVID': 686,
 'GRENFELDT, MATTIAS': 687,
 'OLOFSSON, ASTA': 688,
 'KARLSSON, JESPER': 689,
 'VAN WAVEREN, SANNE': 690,
 'PEK, CHRISTIAN': 691,
 'TORRE, ILARIA': 692,
 'LEITE, IOLANDA': 693,
 'DEKA, SHANKAR A.': 694,
 'PHODAPOL, SUJET': 695,
 'GIMENEZ, ANDREU MATOSES': 696,
 'FERNANDEZ-AYALA, VICTOR NAN': 697,
 'WONG, RUFUS': 698,
 'YU, PIAN': 699,
 'TAN, XIAO': 700,
 'SEGERSTRÖM, PIERRE': 701,
 'BOLTSHAUSER, FELIX': 702,
 'SASAHARA, HAMPEI': 703,
 'SANDBERG, HENRIK': 704,
 'DAHLGREN, CHRISTOFFER': 705,
 'GRAHN, SEBASTIAN': 706,
 'PERESINI, PETER': 707,
 'KUZNIAR, PETER': 708,
 'RABI, MABEN': 709,
 'JOHANSSON, KARL HENRIK': 710,
 'FLOREZ CARDENAS, MATEO': 711,
 'ACAR, GABRIEL': 712,
 'BOMAN, JOAKIM': 713,
 'VOLMINGER, ALEXANDER': 714,
 'RUNHEM, LOVISA': 715,
 'SCHULZE, FILIP': 716,
 'VATN, NIKLAS': 717,
 'BYSTRÖM, JULIA': 718,
 'LIU, WILLY': 719,
 'PARHIZGAR, DANIEL': 720,
 'NORELIUS, JENNY': 721,
 'TACCHI, ANTONELLO': 722,
 'SVENSSON, ERIK R.': 723,
 'LAGERQVIST, KLAS': 724,
 'SALAM PATROUS, ZIAD': 725,
 'NAJAFI, SAFIR': 726,
 'JARWALLI, SABA': 727,
 'ESTEBAN, MASAYA': 728,
 'PERNLER, EMIL': 729,
 'VAINIO, LEO': 730,
 'SUNDIN, HANNES': 731,
 'JOSEFSSON, JAKOB': 732,
 'LÖVSTRÖM, ANTON': 733,
 'STEEN, ANDERS': 734,
 'VON GEGERFELT, ANGELINA': 735,
 'KLINGESTEDT, KASHMIR': 736,
 'AHLSTRAND, EDWIN': 737,
 'ABRAHAMSSON, MÅNS': 738,
 'ALKAZAZ, AYHAM': 739,
 'SAADO KHAROUKI, MARWA': 740,
 'HELLBERG, SIMON': 741,
 'HOLLIDT, DOMINIK': 742,
 'LIDFELDT, GUSTAF': 743,
 'HASSBRING, ISAK': 744,
 'LINDQVIST, NIKLAS': 745,
 'PRICE, THONY': 746,
 'NYGREN, RASMUS': 747,
 'PETKOV, ALEKS': 748,
 'STIERNBORG, SEBASTIAN': 749,
 'ERVIK, SARA': 750,
 'DANG, ROBIN': 751,
 'NILSSON, ANDERS': 752,
 'BEHNAM, HUMAM': 753,
 'MIRZAIAN, ARTIN': 754,
 'AL-QAYSI, BASHAR': 755,
 'BJÖRK, SARA': 756,
 'EKBLAD VOLTAIRE, FANNY': 757,
 'MANNBERG, NOAH': 758,
 'JONSSON, TIM': 759,
 'TAPPER, ISABELLA': 760,
 'ROSBACKE, M.': 761,
 'BJÖRKMAN, E.': 762,
 'ROLAND, P. E.': 763,
 'RODRÍGUEZ-CANO, GUILLERMO': 764,
 'GRESCBACH, BENJAMIN': 765,
 'BUCHEGGER, SONJA': 766,
 'TEGELUND, BJÖRN': 767,
 'ONORI, MAURO': 768,
 'SEMERE, DANIEL': 769,
 'LINDBERG, BENGT': 770,
 'JAGELID, NICOLE': 771,
 'KINDBERG, LUDVIG': 772,
 'NYMAN, NICK': 773,
 'POSTIGO SMURA, MICHEL': 774,
 'RAGNAR, NICLAS': 775,
 'TOLIC, ZORAN': 776,
 'WESTLUND, JOHANNES': 777,
 'SVENNINGSSON, JAKOB': 778,
 'HAMRIN, NIKLAS': 779,
 'RUNEBJÖRK, NILS': 780,
 'BROSTRÖM, JONATHAN': 781,
 'NILSSON, MÅNS': 782,
 'AHLQVIST, OSCAR': 783,
 'ÅKERMARK, WILHELM': 784,
 'JANSON, ALEXANDER': 785,
 'ERIK, SNICKARE': 786,
 'TSAKNAKI, VASILIKI': 787,
 'HEMGREN, DAN': 788,
 'WIDERBERG, ERNST': 789,
 'LORENZEN, JOHAN': 790,
 'PERKOLA, WILLIAM': 791,
 'DWYER, JACOB': 792,

In [9]:
# Write id-to-author file
with open(SAVE_GRAPH_PATH+'id-to-author.csv', 'w') as file:
    file.write(f'id;name\n')
    for author_name, author_id in author_ids.items():
        file.write(f"{author_id};{author_name}\n")

# Write the n-hop neighbours lists

In [28]:
def n_hop_neighbours(G, node, n):
    '''
    '''
    visited = set([node])
    current_layer = set([node])
    hop_neighbors = []

    for _ in range(n):
        next_layer = set()
        for u in current_layer:
            neighbors = set(G.neighbors(u)) - visited
            next_layer |= neighbors
        hop_neighbors.append(list(next_layer))
        visited |= next_layer
        current_layer = next_layer

    return hop_neighbors

In [31]:
def write_graph(path, n_degrees):
    assert type(n_degrees) == int and n_degrees >= 1, 'n_degrees must be an int >= 1'
    with open(path+f'graph.csv', 'w') as file:
        # Write first row
        first_row = 'node'
        for i in range(1, n_degrees+1):
            first_row += f';{i}_hop_neighbours'
        file.write(first_row + '\n')
        # Write rows
        for node in g.nodes:
            line = f'{author_ids[node]}'
            neighbour_lists = n_hop_neighbours(G=g, node=node, n=n_degrees)
            for neighbour_list in neighbour_lists:
                neighbours_string = [author_ids[name] for name in neighbour_list]
                line += f';{neighbours_string}'
            file.write(line + '\n')

In [32]:
write_graph(path=SAVE_GRAPH_PATH, n_degrees=3)

In [ ]:
df = pd.read_csv('graph/graph.csv', sep=';')

   node 1_hop_neighbours 2_hop_neighbours 3_hop_neighbours
0     0              [1]               []               []
1     1              [0]               []               []
2     2              [3]               []               []
3     3              [2]               []               []
4     4              [5]               []               []